name: PR

permissions:
  contents: write
  
on:
  pull_request:
  merge_group:

concurrency:
  group: shopify-cli-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DEBUG: '1'
  SHOPIFY_CLI_ENV: development
  SHOPIFY_CONFIG: debug
  PNPM_VERSION: '10.11.1'
  BUNDLE_WITHOUT: 'test:development'
  GH_TOKEN_CUSTOM: ${{ secrets.SHOPIFY_GH_READ_CONTENT_TOKEN }}
  GH_TOKEN_SHOP: ${{ secrets.SHOP_GH_READ_CONTENT_TOKEN }}
  DEFAULT_NODE_VERSION: '26.1.0'
  PLAYWRIGHT_NODE_VERSION: '24.1.0'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  type-check:
    name: 'Type check'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name == 'merge_group'
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.event.repository.full_name }}
          ref: ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref }}
          fetch-depth: 1
      - name: Setup deps
        uses: ./.github/actions/setup-cli-deps
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - name: Type check
        run: pnpm nx run-many --all --skip-nx-cache --target=type-check --output-style=stream
